on: pull_request

name: Check Code Style (checkpatch)

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DL_DIR: ../downloads
      BUILD_DIR: ../build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Install required packages (apt-get)
        run: |
            sudo apt-get update
            sudo apt-get install patchutils
      - name: Run checkpatch
        run: |
            cnt=$(git rev-list --count HEAD ^origin/riscv)
            echo "commit count:$cnt"
            git diff HEAD~${cnt} \
            | filterdiff \
                -x "a/src/jtag/drivers/libjaylink/*" \
                -x "a/tools/git2cl/*" \
                -x "a/.github/*" \
                -x "a/HACKING" \
            | ./tools/scripts/checkpatch.pl --no-signoff -
