on: pull_request

name: Sparse

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DL_DIR: ../downloads
      BUILD_DIR: ../build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Checkout Base
        run: |
            git fetch origin ${{ github.event.pull_request.base.ref }}
            echo "The current base for checkpatch is: $(git show FETCH_HEAD --oneline --raw)"
      - name: Install required packages (apt-get)
        run: |
            sudo apt-get update
            sudo apt-get install sparse
      - name: Run Sparse tool
        env:
          SPARSE_BUILD_OUTDIR: "sparse"
          SPARSE_BUILD_OUTFILE: "warnings.log"
        run: |
            ./bootstrap
            ./configure CC=cgcc CFLAGS="-Wsparse-all -Wno-declaration-after-statement -Wno-unknown-attribute -Wno-transparent-union -Wno-tautological-compare -Wno-vla -Wno-flexible-array-array -D__FLT_EVAL_METHOD__=0"
            ((make -j`nproc`) 1> >(tee make.log)) 2> >(tee ${SPARSE_BUILD_OUTFILE} 2>&2)
            echo $(wc -l < ${SPARSE_BUILD_OUTFILE}) "sparse warning found"
            grep -i -e "riscv/*" ${SPARSE_BUILD_OUTFILE}
